### ISSUE TITLE
Some recommendations/suggestions

### ISSUE THREAD

**Issue by bm3719** [AbbyJoy/movie-app#1]
Some thoughts occurred to me while reading the current state of the code:
- In response/get-movie-reviews, you grab all of the reviews.
- In response/get-movie-by-id, the error handling here could have some negative side-effects.
- The original data had stars always be in the form of d.d.  We could do the same here pretty easily.
- Recommend storing the integer version of the review rating on ingest.

**Comment by AtticusJoy** [comment]
@bm3719 
- For response/get-movie-reviews, it returns only the reviews associated with the movie. Are you saying that I should only get the reviews associated with the movie in the first place?
- For response/get-movie-by-id, are you pointing out that the application doesn't handle an invalid id well? Or is it that I should do a different kind of error handling?

I think I understand the other two bullets.

**Comment by AtticusJoy** [comment]
This issue has been decomposed into 4 other issues. When closed, this issue will be resolved.
